name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.12.5
    steps:
      - uses: actions/checkout@v3
      - name: Change ownership of /github/home
        run: chown -R $(whoami) /github/home
      - name: Create environment
        run: python3 -m venv .venv
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Cache environment
        uses: actions/cache@v3
        with:
          key: venv
          path: .venv/
  unit-test:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: python:3.12.5
    steps:
      - name: Restore cached environment
        uses: actions/cache/restore@v3
        with:
          key: venv
          path: .venv/
      - name: Activate environment
        run: source .venv/bin/activate
      - name: Execute test with coverage
        run: coverage run -m pytest
      - name: Show coverage on console
        run: coverage report
      - name: Generate html coverage report
        run: coverage html
      - uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov/
  deploy:
    needs: [build, unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy by hook
        run: curl -X POST $RENDER_DEPLOY_HOOK > deploy.json
      - name: Sleep by two minutes
        run: sleep 120
      - uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: deploy.json
