name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.12.5
    steps:
      - uses: actions/checkout@v3
      - name: Change ownership of /github/home
        run: chown -R $(whoami) /github/home
      - name: Create environment
        run: python3 -m venv .venv
      - name: Install dependencies
        run: pip install -r requirements.txt
  unit-test:
    needs: [build]
    runs-on: ubuntu-latest
    container:
      image: python:3.12.5
    steps:
      - uses: actions/checkout@v3
      - name: Change ownership of /github/home
        run: chown -R $(whoami) /github/home
      - name: Create environment
        run: python3 -m venv .venv
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Execute test with coverage
        run: coverage run -m pytest
      - name: Show coverage on console
        run: coverage report
      - name: Generate html coverage report
        run: coverage html
      - name: Generate xml coverage report
        run: coverage xml
      - uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov/
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
  deploy:
    needs: [build, unit-test]
    runs-on: ubuntu-latest
    env:
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
    steps:
      - name: Deploy by hook
        run: curl -X POST $RENDER_DEPLOY_HOOK > deploy.json
      - name: Sleep by two minutes
        run: sleep 120
      - uses: actions/upload-artifact@v4
        with:
          name: deploy
          path: deploy.json
